version: '3'
services:
  web:
    build:
      context: .
      dockerfile: php.dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./projects/example-app:/var/www/projects/example-app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY_HERE
    command: bash -c "composer install --no-dev --optimize-autoloader && chown -R www-data:www-data /var/www/projects/example-app/storage /var/www/projects/example-app/bootstrap/cache && php-fpm"

  web-server:
    image: nginx:1.21.1
    container_name: webdev-nginx
    ports:
      - "4000:80"
      # - "443:443"
    networks:
      - web-dev
    volumes:
      - ./confs/servers/:/etc/nginx/conf.d/
      - ./projects:/var/www/projects
      - ./confs/ssl/:/var/www/ssl

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: webdev-php
    volumes:
      - ./projects:/var/www/projects
    ports:
      - "9001:9000"
    networks:
      - web-dev

  db:
    image: mysql:8.0.33
    container_name: webdev-mysql
    volumes:
      - ./confs/mysql_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    networks:
      - web-dev

networks:
  web-dev:
    driver: bridge
